### ISSUE TITLE
themes are not updating

### ISSUE THREAD

**Issue by jaykayone** [opendatalu/gouvlu#109]
although there are almost 100 datasets selected in the editorial part of the page, there are only 38 shown here:

https://data.public.lu/fr/topics/transports/datasets?sort=-created&page=1

**Comment by noirbizarre** [comment]
This is because it's not meant to work this way.

The editorial selection is only displayed on the topic page (into the **Featured datasets** and **Featured reuses** sections). It should only contains a few but representative datasets.

The link is using a search request filtered on the theme tags (datasets listed here are those having at least on tag mathcing the theme). It there is some datasets missing it means:
- either the theme is missing some tags
- either the missing datasets are missing one of theme tags

I think this is a combination of the two possibilities:
- the topic might lack some tags
- the expected datasets might lack some tags, they required at least one of the topic ones

**Comment by mayjolux** [comment]
Closing, as this is solved.
